alias ls="ls --human-readable --color=auto"
alias df="df --human-readable"
alias du="du --human-readable"
alias mkdir="mkdir --parents"
alias vim="nvim"
alias nb="newsboat"
alias gs="git status"
alias gd="git diff"
alias o="xdg-open"
alias yt="pipe-viewer"
alias gs="git status"
alias gd="git diff"
alias gc="git commit"
alias ga="git add"
alias sv="mosh sven@svenmoeller.xyz -- screen -R"

wordlist="$(bm -h | sed -n '/\t/p' | awk '{print $1}' | sort | tr '\n' ' ')"
complete -W "$wordlist" bm
