alias ls="ls --human-readable --color=auto"
alias df="df --human-readable"
alias du="du --human-readable"
alias mkdir="mkdir --parents"
alias vim="nvim"
alias pass="gopass"
alias mutt="neomutt"
alias nb="newsboat"
alias o="xdg-open"
alias yt="pipe-viewer"
alias gs="git status"
alias gd="git diff"
alias gc="git commit"
alias ga="git add"
alias gr="git restore"
alias sv="mosh sven@svenmoeller.xyz"
alias cg="git -C ~/.dotfiles"
alias cgs="git -C ~/.dotfiles status"
alias cgd="git -C ~/.dotfiles diff"
alias cgc="git -C ~/.dotfiles commit"
alias cgp="git -C ~/.dotfiles push"
alias cgr="git -C ~/.dotfiles restore"
alias cga="git -C ~/.dotfiles add"
alias cs="stow -d ~/.dotfiles"
alias sf="sfeed_curses ~/.sfeed/feeds/*"
alias w3m="w3m -B"
alias search="surfraw search"
alias t="todo.sh"

if [ -z "$DISPLAY" ]; then
	export BROWSER="w3m"
	export DOCVIEWER="jfbview --zoom_to_fit"
	export PICVIEWER="mpv --loop-file=inf --really-quiet"
	export TERMINAL="tmux new-window"

	export SFEED_PLUMBER_INTERACTIVE="1"
fi
